INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (13, "CHARGE", "NORMAL", 25, 0.06, 4000, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (13,"fr-fr","Ligotage");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (13,"en-us","Wrap");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (13,"de-de","Wrap");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (14, "CHARGE", "NORMAL", 120, 0.15, 5000, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (14,"fr-fr","Ultralaser");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (14,"en-us","Hyper Beam");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (14,"de-de","Hyper Beam");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (16, "CHARGE", "DARK", 45, 0.08, 3500, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (16,"fr-fr","Vibrobscur");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (16,"en-us","Dark Pulse");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (16,"de-de","Dark Pulse");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (18, "CHARGE", "POISON", 30, 0.065, 2600, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (18,"fr-fr","Détritus");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (18,"en-us","Sludge");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (18,"de-de","Sludge");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (20, "CHARGE", "NORMAL", 25, 0.055, 2100, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (20,"fr-fr","Force Poigne");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (20,"en-us","Vice Grip");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (20,"de-de","Vice Grip");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (21, "CHARGE", "FIRE", 40, 0.06, 4600, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (21,"fr-fr","Roue de Feu");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (21,"en-us","Flame Wheel");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (21,"de-de","Flame Wheel");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (22, "CHARGE", "BUG", 80, 0.12, 3200, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (22,"fr-fr","Mégacorne");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (22,"en-us","Megahorn");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (22,"de-de","Megahorn");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (24, "CHARGE", "FIRE", 55, 0.09, 2900, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (24,"fr-fr","Lance Flamme");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (24,"en-us","Flamethrower");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (24,"de-de","Flamethrower");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (26, "CHARGE", "GROUND", 70, 0.08, 5800, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (26,"fr-fr","Tunnel");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (26,"en-us","Dig");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (26,"de-de","Dig");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (28, "CHARGE", "FIGHTING", 60, 0.1, 2000, -100, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (28,"fr-fr","Coup-Croix");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (28,"en-us","Cross Chop");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (28,"de-de","Cross Chop");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (30, "CHARGE", "PSYCHIC", 40, 0.065, 3800, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (30,"fr-fr","Rafale Psy");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (30,"en-us","Psybeam");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (30,"de-de","Psybeam");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (31, "CHARGE", "GROUND", 100, 0.1, 4200, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (31,"fr-fr","Séisme");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (31,"en-us","Earthquake");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (31,"de-de","Earthquake");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (32, "CHARGE", "ROCK", 80, 0.1, 3100, -100, 0.5);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (32,"fr-fr","Lame de roc");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (32,"en-us","Stone Edge");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (32,"de-de","Stone Edge");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (33, "CHARGE", "ICE", 45, 0.075, 3500, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (33,"fr-fr","Poing de Glace");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (33,"en-us","Ice Punch");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (33,"de-de","Ice Punch");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (34, "CHARGE", "PSYCHIC", 20, 0.06, 2550, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (34,"fr-fr","Crèvecoeur");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (34,"en-us","Heart Stamp");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (34,"de-de","Heart Stamp");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (35, "CHARGE", "ELECTRIC", 35, 0.08, 2500, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (35,"fr-fr","Coup d'Jus");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (35,"en-us","Discharge");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (35,"de-de","Discharge");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (36, "CHARGE", "STEEL", 60, 0.08, 3900, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (36,"fr-fr","Luminocanon");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (36,"en-us","Flash Cannon");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (36,"de-de","Flash Cannon");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (38, "CHARGE", "FLYING", 40, 0.08, 2700, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (38,"fr-fr","Bec Vrille");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (38,"en-us","Drill Peck");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (38,"de-de","Drill Peck");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (39, "CHARGE", "ICE", 65, 0.09, 3650, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (39,"fr-fr","Laser Glace");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (39,"en-us","Ice Beam");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (39,"de-de","Ice Beam");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (40, "CHARGE", "ICE", 100, 0.11, 3900, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (40,"fr-fr","Blizzard");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (40,"en-us","Blizzard");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (40,"de-de","Blizzard");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (42, "CHARGE", "FIRE", 80, 0.095, 3800, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (42,"fr-fr","Canicule");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (42,"en-us","Heat Wave");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (42,"de-de","Heat Wave");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (45, "CHARGE", "FLYING", 30, 0.06, 2900, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (45,"fr-fr","Aéropique");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (45,"en-us","Aerial Ace");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (45,"de-de","Aerial Ace");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (46, "CHARGE", "GROUND", 50, 0.08, 3400, -33, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (46,"fr-fr","Tunnelier");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (46,"en-us","Drill Run");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (46,"de-de","Drill Run");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (47, "CHARGE", "GRASS", 65, 0.09, 3200, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (47,"fr-fr","Tempête Florale");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (47,"en-us","Petal Blizzard");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (47,"de-de","Petal Blizzard");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (48, "CHARGE", "GRASS", 15, 0.04, 3200, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (48,"fr-fr","Méga Sangsue");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (48,"en-us","Mega Drain");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (48,"de-de","Mega Drain");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (49, "CHARGE", "BUG", 75, 0.09, 4250, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (49,"fr-fr","Bourdon");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (49,"en-us","Bug Buzz");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (49,"de-de","Bug Buzz");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (50, "CHARGE", "POISON", 25, 0.05, 2400, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (50,"fr-fr","Crochet Venin");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (50,"en-us","Poison Fang");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (50,"de-de","Poison Fang");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (51, "CHARGE", "DARK", 30, 0.07, 2700, -25, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (51,"fr-fr","Tranche-Nuit");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (51,"en-us","Night Slash");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (51,"de-de","Night Slash");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (53, "CHARGE", "WATER", 30, 0.065, 2900, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (53,"fr-fr","Bulle d'O");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (53,"en-us","Bubble Beam");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (53,"de-de","Bubble Beam");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (54, "CHARGE", "FIGHTING", 30, 0.08, 2100, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (54,"fr-fr","Sacrifice");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (54,"en-us","Submission");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (54,"de-de","Submission");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (56, "CHARGE", "FIGHTING", 30, 0.065, 2250, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (56,"fr-fr","Balayette");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (56,"en-us","Low Sweep");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (56,"de-de","Low Sweep");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (57, "CHARGE", "WATER", 25, 0.04, 2350, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (57,"fr-fr","Aqua Jet");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (57,"en-us","Aqua Jet");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (57,"de-de","Aqua Jet");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (58, "CHARGE", "WATER", 45, 0.09, 2350, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (58,"fr-fr","Hydroqueue");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (58,"en-us","Aqua Tail");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (58,"de-de","Aqua Tail");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (59, "CHARGE", "GRASS", 40, 0.08, 2400, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (59,"fr-fr","Canon Graine");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (59,"en-us","Seed Bomb");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (59,"de-de","Seed Bomb");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (60, "CHARGE", "PSYCHIC", 40, 0.08, 2700, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (60,"fr-fr","Choc Psy");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (60,"en-us","Psyshock");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (60,"de-de","Psyshock");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (62, "CHARGE", "ROCK", 35, 0.06, 3600, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (62,"fr-fr","Pouvoir Antique");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (62,"en-us","Ancient Power");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (62,"de-de","Ancient Power");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (63, "CHARGE", "ROCK", 30, 0.06, 3400, -25, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (63,"fr-fr","Tomberoche");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (63,"en-us","Rock Tomb");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (63,"de-de","Rock Tomb");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (64, "CHARGE", "ROCK", 50, 0.075, 3200, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (64,"fr-fr","Eboulement");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (64,"en-us","Rock Slide");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (64,"de-de","Rock Slide");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (65, "CHARGE", "ROCK", 40, 0.08, 2900, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (65,"fr-fr","Rayon Gemme");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (65,"en-us","Power Gem");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (65,"de-de","Power Gem");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (66, "CHARGE", "GHOST", 15, 0.04, 3100, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (66,"fr-fr","Ombre Portée");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (66,"en-us","Shadow Sneak");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (66,"de-de","Shadow Sneak");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (67, "CHARGE", "GHOST", 20, 0.06, 2100, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (67,"fr-fr","Poing Ombre");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (67,"en-us","Shadow Punch");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (67,"de-de","Shadow Punch");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (69, "CHARGE", "GHOST", 30, 0.06, 3100, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (69,"fr-fr","Vent Mauvais");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (69,"en-us","Ominous Wind");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (69,"de-de","Ominous Wind");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (70, "CHARGE", "GHOST", 45, 0.08, 3080, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (70,"fr-fr","Ball'Ombre");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (70,"en-us","Shadow Ball");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (70,"de-de","Shadow Ball");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (72, "CHARGE", "STEEL", 30, 0.06, 2800, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (72,"fr-fr","Bombaimant");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (72,"en-us","Magnet Bomb");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (72,"de-de","Magnet Bomb");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (74, "CHARGE", "STEEL", 30, 0.08, 2000, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (74,"fr-fr","Tête de Fer");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (74,"en-us","Iron Head");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (74,"de-de","Iron Head");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (75, "CHARGE", "ELECTRIC", 15, 0.05, 2100, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (75,"fr-fr","Parabocharge");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (75,"en-us","Parabolic Charge");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (75,"de-de","Parabolic Charge");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (77, "CHARGE", "ELECTRIC", 40, 0.075, 2400, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (77,"fr-fr","Poing Eclair");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (77,"en-us","Thunder Punch");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (77,"de-de","Thunder Punch");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (78, "CHARGE", "ELECTRIC", 100, 0.11, 4300, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (78,"fr-fr","Fatal Foudre");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (78,"en-us","Thunder");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (78,"de-de","Thunder");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (79, "CHARGE", "ELECTRIC", 55, 0.09, 2700, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (79,"fr-fr","Tonnerre");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (79,"en-us","Thunderbolt");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (79,"de-de","Thunderbolt");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (80, "CHARGE", "DRAGON", 25, 0.04, 2700, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (80,"fr-fr","Ouragan");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (80,"en-us","Twister");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (80,"de-de","Twister");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (82, "CHARGE", "DRAGON", 65, 0.085, 3600, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (82,"fr-fr","Dracochoc");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (82,"en-us","Dragon Pulse");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (82,"de-de","Dragon Pulse");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (83, "CHARGE", "DRAGON", 35, 0.08, 1500, -50, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (83,"fr-fr","Dracogriffe");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (83,"en-us","Dragon Claw");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (83,"de-de","Dragon Claw");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (84, "CHARGE", "FAIRY", 25, 0.04, 3900, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (84,"fr-fr","Voix Enjôleuse");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (84,"en-us","Disarming Voice");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (84,"de-de","Disarming Voice");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (85, "CHARGE", "FAIRY", 25, 0.05, 2800, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (85,"fr-fr","Vampibaiser");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (85,"en-us","Draining Kiss");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (85,"de-de","Draining Kiss");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (86, "CHARGE", "FAIRY", 55, 0.08, 4200, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (86,"fr-fr","Eclats Magique");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (86,"en-us","Dazzling Gleam");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (86,"de-de","Dazzling Gleam");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (87, "CHARGE", "FAIRY", 85, 0.095, 4100, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (87,"fr-fr","Pouvoir Lunaire");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (87,"en-us","Moonblast");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (87,"de-de","Moonblast");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (88, "CHARGE", "FAIRY", 55, 0.1, 2900, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (88,"fr-fr","Câlinerie");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (88,"en-us","Play Rough");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (88,"de-de","Play Rough");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (89, "CHARGE", "POISON", 25, 0.07, 1500, -25, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (89,"fr-fr","Poison-Croix");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (89,"en-us","Cross Poison");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (89,"de-de","Cross Poison");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (90, "CHARGE", "POISON", 55, 0.09, 2600, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (90,"fr-fr","Bomb beurk");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (90,"en-us","Sludge Bomb");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (90,"de-de","Sludge Bomb");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (91, "CHARGE", "POISON", 70, 0.095, 3400, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (91,"fr-fr","Cradovague");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (91,"en-us","Sludge Wave");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (91,"de-de","Sludge Wave");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (92, "CHARGE", "POISON", 65, 0.12, 3000, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (92,"fr-fr","Détricanon");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (92,"en-us","Gunk Shot");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (92,"de-de","Gunk Shot");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (94, "CHARGE", "GROUND", 25, 0.065, 1600, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (94,"fr-fr","Mass d'Os");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (94,"en-us","Bone Club");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (94,"de-de","Bone Club");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (95, "CHARGE", "GROUND", 35, 0.06, 3400, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (95,"fr-fr","Piétisol");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (95,"en-us","Bulldoze");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (95,"de-de","Bulldoze");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (96, "CHARGE", "GROUND", 30, 0.065, 2600, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (96,"fr-fr","Boue Bombe");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (96,"en-us","Mud Bomb");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (96,"de-de","Mud Bomb");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (99, "CHARGE", "BUG", 45, 0.075, 3100, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (99,"fr-fr","Rayon Signal");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (99,"en-us","Signal Beam");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (99,"de-de","Signal Beam");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (100, "CHARGE", "BUG", 35, 0.08, 2100, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (100,"fr-fr","Plaie-Croix");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (100,"en-us","X Scissor");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (100,"de-de","X Scissor");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (101, "CHARGE", "FIRE", 25, 0.05, 3100, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (101,"fr-fr","Nitrocharge");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (101,"en-us","Flame Charge");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (101,"de-de","Flame Charge");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (102, "CHARGE", "FIRE", 30, 0.07, 2100, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (102,"fr-fr","Rebondifeu");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (102,"en-us","Flame Burst");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (102,"de-de","Flame Burst");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (103, "CHARGE", "FIRE", 100, 0.11, 4100, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (103,"fr-fr","Déflagration");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (103,"en-us","Fire Blast");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (103,"de-de","Fire Blast");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (104, "CHARGE", "WATER", 25, 0.065, 2400, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (104,"fr-fr","Saumure");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (104,"en-us","Brine");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (104,"de-de","Brine");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (105, "CHARGE", "WATER", 35, 0.06, 3300, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (105,"fr-fr","Vibraqua");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (105,"en-us","Water Pulse");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (105,"de-de","Water Pulse");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (106, "CHARGE", "WATER", 55, 0.08, 4000, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (106,"fr-fr","Ebullition");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (106,"en-us","Scald");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (106,"de-de","Scald");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (107, "CHARGE", "WATER", 90, 0.11, 3800, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (107,"fr-fr","Hydrocanon");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (107,"en-us","Hydro Pump");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (107,"de-de","Hydro Pump");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (108, "CHARGE", "PSYCHIC", 55, 0.09, 2800, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (108,"fr-fr","Psyko");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (108,"en-us","Psychic");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (108,"de-de","Psychic");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (109, "CHARGE", "PSYCHIC", 70, 0.1, 5100, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (109,"fr-fr","Frappe Psy");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (109,"en-us","Psystrike");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (109,"de-de","Psystrike");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (111, "CHARGE", "ICE", 25, 0.055, 3800, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (111,"fr-fr","Vent Glace");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (111,"en-us","Icy Wind");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (111,"de-de","Icy Wind");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (114, "CHARGE", "GRASS", 35, 0.075, 3600, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (114,"fr-fr","Giga-Sangsue");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (114,"en-us","Giga Drain");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (114,"de-de","Giga Drain");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (115, "CHARGE", "FIRE", 40, 0.075, 2800, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (115,"fr-fr","Poing de Feu");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (115,"en-us","Fire Punch");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (115,"de-de","Fire Punch");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (116, "CHARGE", "GRASS", 120, 0.12, 4900, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (116,"fr-fr","Lance-Soleil");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (116,"en-us","Solar Beam");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (116,"de-de","Solar Beam");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (117, "CHARGE", "GRASS", 55, 0.09, 2800, -50, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (117,"fr-fr","Lame Feuille");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (117,"en-us","Leaf Blade");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (117,"de-de","Leaf Blade");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (118, "CHARGE", "GRASS", 70, 0.12, 2800, -100, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (118,"fr-fr","Mégafouet");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (118,"en-us","Power Whip");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (118,"de-de","Power Whip");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (121, "CHARGE", "FLYING", 30, 0.06, 3300, -25, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (121,"fr-fr","Tranch'Air");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (121,"en-us","Air Cutter");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (121,"de-de","Air Cutter");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (122, "CHARGE", "FLYING", 80, 0.11, 3200, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (122,"fr-fr","Vent Violent");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (122,"en-us","Hurricane");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (122,"de-de","Hurricane");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (123, "CHARGE", "FIGHTING", 30, 0.075, 1600, -33, 0.25);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (123,"fr-fr","Casse Brique");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (123,"en-us","Brick Break");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (123,"de-de","Brick Break");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (125, "CHARGE", "NORMAL", 30, 0.06, 3000, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (125,"fr-fr","Météores");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (125,"en-us","Swift");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (125,"de-de","Swift");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (126, "CHARGE", "NORMAL", 25, 0.065, 2200, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (126,"fr-fr","Koud'Korne");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (126,"en-us","Horn Attack");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (126,"de-de","Horn Attack");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (127, "CHARGE", "NORMAL", 30, 0.065, 2100, -25, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (127,"fr-fr","Ecrasement");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (127,"en-us","Stomp");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (127,"de-de","Stomp");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (129, "CHARGE", "NORMAL", 35, 0.08, 2100, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (129,"fr-fr","Croc de Mort");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (129,"en-us","Hyper Fang");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (129,"de-de","Hyper Fang");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (131, "CHARGE", "NORMAL", 40, 0.085, 1560, -50, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (131,"fr-fr","Plaquage");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (131,"en-us","Body Slam");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (131,"de-de","Body Slam");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (132, "CHARGE", "NORMAL", 35, 0, 3100, -33, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (132,"fr-fr","Repos");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (132,"en-us","Rest");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (132,"de-de","Rest");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (133, "CHARGE", "NORMAL", 15, 0.1, 1695, -20, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (133,"fr-fr","Lutte");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (133,"en-us","Struggle");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (133,"de-de","Struggle");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (134, "CHARGE", "WATER", 35, 0.08, 4000, -33, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (134,"fr-fr","Ebullition Tortank");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (134,"en-us","Scald Blastoise");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (134,"de-de","Scald Blastoise");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (135, "CHARGE", "WATER", 60, 0.11, 3800, -100, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (135,"fr-fr","Hydrocanon Tortank");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (135,"en-us","Hydro Pump Blastoise");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (135,"de-de","Hydro Pump Blastoise");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (136, "CHARGE", "NORMAL", 15, 0.06, 3700, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (136,"fr-fr","Ligotage Vert");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (136,"en-us","Wrap Green");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (136,"de-de","Wrap Green");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (137, "CHARGE", "NORMAL", 15, 0.06, 3700, -20, 0.05);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (137,"fr-fr","Ligotage Rose");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (137,"en-us","Wrap Pink");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (137,"de-de","Wrap Pink");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (200, "QUICK", "BUG", 3, 0.01, 400, 6, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (200,"fr-fr","Taillade");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (200,"en-us","Fury Cutter");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (200,"de-de","Fury Cutter");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (201, "QUICK", "BUG", 5, 0.01, 450, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (201,"fr-fr","Piqûre");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (201,"en-us","Bug Bite");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (201,"de-de","Bug Bite");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (202, "QUICK", "DARK", 6, 0.01, 500, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (202,"fr-fr","Morsure");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (202,"en-us","Bite");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (202,"de-de","Bite");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (203, "QUICK", "DARK", 7, 0.01, 700, 9, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (203,"fr-fr","Sucker Punch");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (203,"en-us","Sucker Punch");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (203,"de-de","Sucker Punch");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (204, "QUICK", "DRAGON", 6, 0.01, 500, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (204,"fr-fr","Draco-souffle");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (204,"en-us","Dragon Breath");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (204,"de-de","Dragon Breath");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (205, "QUICK", "ELECTRIC", 5, 0.01, 600, 8, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (205,"fr-fr","Eclair");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (205,"en-us","Thunder Shock");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (205,"de-de","Thunder Shock");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (206, "QUICK", "ELECTRIC", 7, 0.01, 700, 8, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (206,"fr-fr","Etincelle");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (206,"en-us","Spark");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (206,"de-de","Spark");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (207, "QUICK", "FIGHTING", 5, 0.01, 600, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (207,"fr-fr","Balayage");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (207,"en-us","Low Kick");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (207,"de-de","Low Kick");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (208, "QUICK", "FIGHTING", 6, 0.01, 800, 8, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (208,"fr-fr","Coup Karaté");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (208,"en-us","Karate Chop");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (208,"de-de","Karate Chop");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (209, "QUICK", "FIRE", 10, 0.01, 1050, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (209,"fr-fr","Flammèche");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (209,"en-us","Ember");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (209,"de-de","Ember");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (210, "QUICK", "FLYING", 9, 0.01, 750, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (210,"fr-fr","Cru-Aile");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (210,"en-us","Wing Attack");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (210,"de-de","Wing Attack");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (211, "QUICK", "FLYING", 10, 0.01, 1150, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (211,"fr-fr","Picpic");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (211,"en-us","Peck");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (211,"de-de","Peck");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (212, "QUICK", "GHOST", 5, 0.01, 500, 6, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (212,"fr-fr","Léchouille");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (212,"en-us","Lick");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (212,"de-de","Lick");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (213, "QUICK", "GHOST", 11, 0.01, 950, 8, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (213,"fr-fr","Griffe Ombre");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (213,"en-us","Shadow Claw");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (213,"de-de","Shadow Claw");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (214, "QUICK", "GRASS", 7, 0.01, 650, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (214,"fr-fr","Fouet Lianes");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (214,"en-us","Vine Whip");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (214,"de-de","Vine Whip");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (215, "QUICK", "GRASS", 15, 0.01, 1450, 12, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (215,"fr-fr","Tanche'Herbe");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (215,"en-us","Razor Leaf");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (215,"de-de","Razor Leaf");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (216, "QUICK", "GROUND", 6, 0.01, 550, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (216,"fr-fr","Tir de Boue");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (216,"en-us","Mud Shot");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (216,"de-de","Mud Shot");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (217, "QUICK", "ICE", 15, 0.01, 1400, 12, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (217,"fr-fr","Eclats Glace");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (217,"en-us","Ice Shard");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (217,"de-de","Ice Shard");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (218, "QUICK", "ICE", 9, 0.01, 810, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (218,"fr-fr","Souffle Glacé");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (218,"en-us","Frost Breath");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (218,"de-de","Frost Breath");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (219, "QUICK", "NORMAL", 10, 0.01, 1330, 12, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (219,"fr-fr","Vive Attaque");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (219,"en-us","Quick Attack");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (219,"de-de","Quick Attack");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (220, "QUICK", "NORMAL", 6, 0.01, 500, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (220,"fr-fr","Griffe");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (220,"en-us","Scratch");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (220,"de-de","Scratch");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (221, "QUICK", "NORMAL", 12, 0.01, 1100, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (221,"fr-fr","Charge");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (221,"en-us","Tackle");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (221,"de-de","Tackle");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (222, "QUICK", "NORMAL", 7, 0.01, 540, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (222,"fr-fr","Écras'Face");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (222,"en-us","Pound");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (222,"de-de","Pound");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (223, "QUICK", "NORMAL", 12, 0.01, 1130, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (223,"fr-fr","Coupe");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (223,"en-us","Cut");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (223,"de-de","Cut");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (224, "QUICK", "POISON", 12, 0.01, 1050, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (224,"fr-fr","Direct Toxik");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (224,"en-us","Poison Jab");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (224,"de-de","Poison Jab");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (225, "QUICK", "POISON", 10, 0.01, 1050, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (225,"fr-fr","Acide");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (225,"en-us","Acid");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (225,"de-de","Acid");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (226, "QUICK", "PSYCHIC", 7, 0.01, 570, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (226,"fr-fr","Coupe Psycho");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (226,"en-us","Psycho Cut");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (226,"de-de","Psycho Cut");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (227, "QUICK", "ROCK", 12, 0.01, 1360, 15, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (227,"fr-fr","Jet Pierres");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (227,"en-us","Rock Throw");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (227,"de-de","Rock Throw");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (228, "QUICK", "STEEL", 8, 0.01, 630, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (228,"fr-fr","Griffe Acier");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (228,"en-us","Metal Claw");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (228,"de-de","Metal Claw");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (229, "QUICK", "STEEL", 10, 0.01, 1200, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (229,"fr-fr","Pisto-Poing");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (229,"en-us","Bullet Punch");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (229,"de-de","Bullet Punch");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (230, "QUICK", "WATER", 6, 0.01, 500, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (230,"fr-fr","Pistolet à O");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (230,"en-us","Water Gun");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (230,"de-de","Water Gun");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (231, "QUICK", "WATER", 0, 0.01, 1230, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (231,"fr-fr","Trempette");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (231,"en-us","Splash");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (231,"de-de","Splash");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (232, "QUICK", "WATER", 10, 0.01, 500, 7, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (232,"fr-fr","Pistolet à O Tortank");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (232,"en-us","Water Gun Fast Blastoise");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (232,"de-de","Water Gun Fast Blastoise");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (233, "QUICK", "GROUND", 15, 0.01, 1350, 12, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (233,"fr-fr","Coud'Boue");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (233,"en-us","Mud Slap");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (233,"de-de","Mud Slap");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (234, "QUICK", "PSYCHIC", 12, 0.01, 1050, 9, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (234,"fr-fr","Psykoud'Boul");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (234,"en-us","Zen Headbutt");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (234,"de-de","Zen Headbutt");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (235, "QUICK", "PSYCHIC", 15, 0.01, 1510, 14, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (235,"fr-fr","Choc Mental");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (235,"en-us","Confusion");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (235,"de-de","Confusion");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (236, "QUICK", "POISON", 6, 0.01, 575, 8, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (236,"fr-fr","Drad Venin");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (236,"en-us","Poison Sting");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (236,"de-de","Poison Sting");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (237, "QUICK", "WATER", 25, 0.01, 2300, 25, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (237,"fr-fr","Ecume");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (237,"en-us","Bubble");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (237,"de-de","Bubble");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (238, "QUICK", "DARK", 12, 0.01, 1040, 10, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (238,"fr-fr","Feinte");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (238,"en-us","Feint Attack");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (238,"de-de","Feint Attack");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (239, "QUICK", "STEEL", 15, 0.01, 1330, 12, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (239,"fr-fr","Aile d'Acier");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (239,"en-us","Steel Wing");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (239,"de-de","Steel Wing");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (240, "QUICK", "FIRE", 10, 0.01, 840, 8, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (240,"fr-fr","Croc de Feu");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (240,"en-us","Fire Fang");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (240,"de-de","Fire Fang");
INSERT OR REPLACE INTO move (id, move_type, type, power, stamina_loss_scalar, duration, energy_delta, critical_chance) VALUES (241, "QUICK", "FIGHTING", 15, 0.01, 1410, 12, 0);
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (241,"fr-fr","Eclate Roc");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (241,"en-us","Rock Smash");
INSERT OR REPLACE INTO move_i18n (id,lang,name) VALUES (241,"de-de","Rock Smash");
